### ISSUE TITLE
problem with iris 1.2.6

### ISSUE THREAD

**Issue by cold233** [leon-o/iris-flw-compat#1]
ghost image of entities and blocks optimized by flywheel appears in player's view:
multiple shaderpacks tested and the problem still exist.
screenshoots:
ComplementaryShaders_v4.5.1:
![2022-08-16_09 26 46](https://user-images.githubusercontent.com/54432054/184780319-1aeab4b0-1f5d-4493-b899-d1452df05a17.png)
ComplementaryReimagined_r1.1.1:
![2022-08-16_09 16 41](https://user-images.githubusercontent.com/54432054/184780507-88e538be-f022-4140-9015-76ec7f0ab0e8.png)

besides, some warnings popped out when enabling shaderpacks:
![2022-08-16_09 41 14](https://user-images.githubusercontent.com/54432054/184780703-a61bcc3b-2141-478e-8e26-f59403b1ef18.png)

additional imformation might be helpful:
game version: 1.18.2
fabric version: 0.14.8
fabric api: 0.58.0
list of mods:
Xaero's minimap 22.12.0
minihud 0.22.0
sodium 0.4.1+build.15
indium 1.0.6
architectury 4.6.77
cloth config 6.2.62
carpet 1.4.69
iris 1.2.6
iris flywheel compat 0.1-ALPHA
malilib 0.12.1
REI 0.12.1
tweakeroo 0.13.3
system : Windows 10 21H2
video card: GTX 1060
video card driver version: 30.0.14.7196
java: 17.0.1

**Comment by leon-o** [comment]
Currently you need to download the patch for the shaderpack in the releases page.
I'm trying to find the way to patch shaderpacks automatically.

**Comment by leon-o** [comment]
Currently you need to download the patch for the shaderpack in the releases page.
I'm trying to find the way to patch shaderpacks automatically.

**Comment by leon-o** [comment]
Already solved.
Download and try the latest version in curseforge.
