### ISSUE TITLE
crash on startup fabric 1.20.1

### ISSUE THREAD

**Issue by NolanHewitt** [leon-o/iris-flw-compat#100]
[crash-2024-02-17_22.47.49-client.txt](https://github.com/leon-o/iris-flw-compat/files/14321195/crash-2024-02-17_22.47.49-client.txt)

**Comment by Sooperfish** [comment]
You have Indium for 1.20.4 installed

**Comment by leon-o** [comment]
You have installed the latest version 1.6.17 of Iris, and it is not compatible with this mod. The issue has been addressed in version 0.2.4.
