### ISSUE TITLE
使用Oculus光影时会导致显卡占用 频率 功耗 乱跳不稳定

### ISSUE THREAD

**Issue by LittleKing2004** [leon-o/iris-flw-compat#101]
游戏版本 1.20.1 forge 47.2.0
机械动力版本 1.20.1-0.5.1.f
飞轮补丁版本 oculus-flywheel-compat-1.20.1-0.2.4
E铷版本：0.3.5+mc1.20.1
Oculus版本：1.20.1-1.6.15a
光影是 ComplementaryReimagined_r5.1.1

使用显卡 AMD RX6600XT 驱动 23.12.1
win 10系统

经过控制变量法，确定了是由于添加 oculus-flywheel-compat-1.20.1-0.2.4 引起的问题。
问题描述：
    启用光影后显卡的占用率会在 60%-95% 之间来回跳动有时候更低。以及频率和功耗都是这样乱跳，无法稳定。删除飞轮补丁后就正常 
    显卡稳定的满载运行。

游戏日志。（未搜索到包含flywheel的信息）
[latest.log](https://github.com/leon-o/iris-flw-compat/files/14393401/latest.log)
debug日志 （这个有）
[debug.log](https://github.com/leon-o/iris-flw-compat/files/14393410/debug.log)

**Comment by leon-o** [comment]
帧数稳定吗？
