### ISSUE TITLE
Crash when loading into world with newest Create version

### ISSUE THREAD

**Issue by Hippopipo** [leon-o/iris-flw-compat#103]
Crashes with newest version of create.
Mods include Create, Fabric API, Indium, Iris, Iris Flywheel compat, Mixintrace and Sodium.
Crash log: https://mclo.gs/f76M3sq
Latest.log: https://mclo.gs/Kp4zaIt

**Comment by PaulRV0709** [comment]
Same exact issue here

**Comment by Emythiel** [comment]
I'm guessing you downloaded from Modrinth?

It seems Curseforge has a slightly newer version for Fabric/Iris - 0.2.4
https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=4

I'm on that one, and haven't gotten any crashes from quick loading into the world (though haven't done long term testing?

**Comment by Hippopipo** [comment]
oh that was it
