### ISSUE TITLE
Modrinth version not updated to latest version.

### ISSUE THREAD

**Issue by Hippopipo** [leon-o/iris-flw-compat#104]

**Comment by Voidmaster01** [comment]
still not (PLS)

**Comment by MrRedstoneToGo** [comment]
It seems that @leon-o has left Github or only checks it very rarely. The problem is that only he can release updates for the Modrinth version.

The CCO 1.0 license does allow reuploads/forks, although I would prefer to do without it.

**Comment by PaulRV0709** [comment]
Please update on modrinth 🙏
