### ISSUE TITLE
Not compatible with the newest version of Create Fabric (0.5.1-f-build.1335+mc1.20.)

### ISSUE THREAD

**Issue by MrRedstoneToGo** [leon-o/iris-flw-compat#106]
Before the update 0.5.1-f Create is incompatible with Sodium, now it is with your mod when joining a world. (I think the world cannot be rendered).

Logs:
[latest.log](https://github.com/leon-o/iris-flw-compat/files/14623305/latest.log)
[crash-2024-03-16_11.54.48-client.txt](https://github.com/leon-o/iris-flw-compat/files/14623307/crash-2024-03-16_11.54.48-client.txt)

**Comment by PhoxVRC** [comment]
Same issue here. Says resource reload failed once you start the game. 
![image](https://github.com/leon-o/iris-flw-compat/assets/42518848/af04fbc6-9c1a-42b3-a608-03c5ad32ca19)
If you attempt to load a world or Join a server the game will crash.

**Comment by PhoxVRC** [comment]
Tried the version on Curseforge and it works fine. The modrinth version seems to be out of date. @MrRedstoneToGo

**Comment by MrRedstoneToGo** [comment]
Is there any way to remind @leon-o?

**Comment by leon-o** [comment]
I’m sorry, I’m too busy these days. Thank you for your reminder, I’ll upload the new version to Modrinth.

**Comment by MrRedstoneToGo** [comment]
Yay!

**Comment by MrRedstoneToGo** [comment]
Thanks a lot! Now I can finallly use this mod in my modpack.
