### ISSUE TITLE
Crashed randomly

### ISSUE THREAD

**Issue by Xch-hq** [leon-o/iris-flw-compat#108]
[crash-2024-03-24_16.46.27-client.txt](https://github.com/leon-o/iris-flw-compat/files/14734917/crash-2024-03-24_16.46.27-client.txt)

**Comment by suerion** [comment]
We had the same Error here.

**Comment by suerion** [comment]
[crash-2024-04-24_17.45.59-client.txt](https://github.com/leon-o/iris-flw-compat/files/15097706/crash-2024-04-24_17.45.59-client.txt)

**Comment by souldbminersmwc** [comment]
Same issue here

**Comment by otomir23** [comment]
Same issues, happens specifically when an item appears/dissapears from the hand of a deployer.

**Comment by Rodrigo816** [comment]
Some problem
[crash-2024-03-24_16.46.27-client.txt](https://github.com/user-attachments/files/16390866/crash-2024-03-24_16.46.27-client.txt)
[crash-2024-06-29_16.56.41-client.txt](https://github.com/user-attachments/files/16390867/crash-2024-06-29_16.56.41-client.txt)

**Comment by leon-o** [comment]
Same issue with #125, which is fixed by the pull #141.
