### ISSUE TITLE
实体阴影闪烁

### ISSUE THREAD

**Issue by shanoaice** [leon-o/iris-flw-compat#11]
这个模组似乎会忽略光影包（已测试`Complementary Reimagined`）的实体阴影设定，导致 Create 多方块结构的阴影总是会渲染。在光影设置里将实体阴影关掉，当背对移动中的 Create 多方块结构时，该结构的阴影会逐渐开始闪烁。在光影设置中启用实体阴影后问题即解决。在光影设置中启用实体阴影后问题即解决。

edit: 大致有一些想法了，我猜测可能是 Entity Culling 导致背后的实体不渲染产生的问题

[实体阴影闪烁.webm](https://user-images.githubusercontent.com/25174488/188321551-4d5d471f-3233-4984-afc4-8b53804e1e00.webm)

**Comment by leon-o** [comment]
抱歉这么久才来回复。
这个问题其实我很早就注意到了，装上entityculling这个模组之后，背对着Create的风车时，风车好像会以最高速旋转。
但是我记得没装iris-flw-compat的时候也会有这个问题，这应该不是iris-flw-compat导致的。

**Comment by shanoaice** [comment]
是的，我也发现是这个问题
也许我该去和 EntityCulling 的作者报告这个问题
