### ISSUE TITLE
1.20.1fabric--Unable to enter the world

### ISSUE THREAD

**Issue by chenye041208** [leon-o/iris-flw-compat#113]
[错误报告-2024-4-12_16.21.37.zip](https://github.com/leon-o/iris-flw-compat/files/14956125/-2024-4-12_16.21.37.zip)
[错误报告-2024-4-12_16.29.54.zip](https://github.com/leon-o/iris-flw-compat/files/14956205/-2024-4-12_16.29.54.zip)

There are two bug reports here.
Able to enter the game normally, but unable to enter the world

**Comment by leon-o** [comment]
Please use version 0.2.4 instead, because you are using Iris 1.6.17, which is not supported by 0.2.1.

请用0.2.4版本的。因为你用了iris 1.6.17，0.2.1版本是不支持的。
