### ISSUE TITLE
[SMALL ISSUE] Mod files not ordered in modrinth

### ISSUE THREAD

**Issue by PaulRV0709** [leon-o/iris-flw-compat#119]
When I do "check for updates", it tries to update from the 0.2.5 to the 0.2.4 version of this mod, I also saw in a dropdown for selecting the version of this mod when downloading it (in Prism launcher it) that the 0.2.4 was above the 0.2.5 version.
Small issue since all it causes is that my mod updater always try to "update" the mod to the wrong version.

**Comment by leon-o** [comment]
It seems like I need to delete version 0.2.5 of the mods and re-upload them to correct the order. Does anyone know how to fix this without deleting the files?
