### ISSUE TITLE
Flywheel crush?

### ISSUE THREAD

**Issue by ElenaNya** [leon-o/iris-flw-compat#120]
oculus-flywheel-compat-1.20.1-0.2.5
oculus-mc1.20.1-1.7.0
DistantHorizons-forge-2.0.4-a-dev-1.20.1
just in case, the Sinytra Connector is installed, but mods for Forge

Minecraft: 1.20.1
Forge: 47.2.30

The game just closes without giving any error, if I understand correctly - it happens if you go and load something from Create, no crash-report, only log.

[latest.log](https://github.com/leon-o/iris-flw-compat/files/15347691/latest.log)

![image](https://github.com/leon-o/iris-flw-compat/assets/94359925/29d09749-aa4f-471b-b940-7505edfd0269)

**Comment by Seba244c** [comment]
Same crash here. (Logs [https://mclo.gs/pAcY7Rk#L9441](https://mclo.gs/pAcY7Rk#L9441))
`java.lang.IllegalStateException: Not filled all elements of the vertex  at com.mojang.blaze3d.vertex.BufferBuilder.m_5752_(BufferBuilder.java:264)`

With Oculus, Flywehel and this mod. Crashed whenever I put an item into a deployer. Disabling the two mods fixed the issue, and when re-enabled I could use the world again. But today it randomly crashed whilst i was looking at my contraption

**Comment by leon-o** [comment]
Same issue with #125, which is fixed by the pull #141.
