### ISSUE TITLE
Complementary Reimagined v5.2 Visual Bug caused by Iris Flywheel Compat

### ISSUE THREAD

**Issue by SonofRanman66** [leon-o/iris-flw-compat#121]
![image](https://github.com/leon-o/iris-flw-compat/assets/67488494/c82dd980-d7be-45b6-a65e-10a9914e22d3)
When using this new feature "Advanced Colored Lighting" Occasionally there is a Spider like Shadow that can span across the terrain from your location.
![SpiderShadow](https://github.com/leon-o/iris-flw-compat/assets/67488494/b76ad101-ef79-4d9c-a655-d8e7945bbc8a)

I spoke to the Shader Devs about this on their Discord, and said it's most likely caused by this compatibility mod. Tried it without it, and all worked fine, so here I am posting this. Let me know if there is anything else I can provide to find a solution to this.

Version 1.20.1 Flywheel Compat 1.7+ Iris

**Comment by leon-o** [comment]
Same issue with #89. This issue has been fixed.
