### ISSUE TITLE
游戏崩溃

### ISSUE THREAD

**Issue by INV-PLA** [leon-o/iris-flw-compat#122]
[latest.log](https://github.com/leon-o/iris-flw-compat/files/15396932/latest.log)
模组列表
（优化）（光影）（客户端）oculus-mc1.20.1-1.7.0
（优化）（客户端）embeddium-0.3.18+mc1.20.1-all
（优化）（客户端）embeddiumplus-1.20.1-v1.2.12
（优化）（客户端）oculus-flywheel-compat-1.20.1-0.2.5
机械动力create-1.20.1-0.5.1.f

**Comment by INV-PLA** [comment]
放置机械手拿扳手切换形态或给与物品切换形态都会导致游戏崩溃

**Comment by Oveln** [comment]
I have the same problem.

**Comment by leon-o** [comment]
可以提供日志吗？

**Comment by INV-PLA** [comment]
[新的世界 (13).zip](https://github.com/user-attachments/files/15598268/13.zip)

**Comment by RookiesTwo** [comment]
触发这个bug需要不开启光影

**Comment by leon-o** [comment]
Same issue with #125, which is fixed by the pull #141.
