### ISSUE TITLE
Minecraft infinetly reloading on texture loading

### ISSUE THREAD

**Issue by mikkerlo** [leon-o/iris-flw-compat#124]
Hey! I have this error when trying to load this mod 
"java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'java.lang.Iterable net.coderbot.iris.gl.shader.StandardMacros.createStandardEnvironmentDefines()'"
My versions here:
iris-flw-complat: 0.2.1
sodium: mc1.19.2-0.4.4
iris: 1.6.11+1.19.2
lithium: mc1.19.2-0.11.1
Log is attached
[2024-06-09-4.log](https://github.com/user-attachments/files/15753280/2024-06-09-4.log)

**Comment by EntityinArray** [comment]
Experiencing the same issue with the same setup. Upon startup minecraft shows looping loading screen

**Comment by leon-o** [comment]
Try the latest version. If this issue still exists, please open a new issue.
