### ISSUE TITLE
Crash when Create Portable Storage Interface's connect

### ISSUE THREAD

**Issue by foxynotail** [leon-o/iris-flw-compat#125]
Error: Not filled all elements of the vertex

Doesn't happen every time. 
Strangely, this mostly happens when shaders are not enabled.

I propose that this mod is worked so that it does not do anything at all, unless a shader is enabled.

**Comment by zarunet** [comment]
Can confirm, suffering the same crashes. I was able to reproduce this :
- without any shader enabled
- both on Fabric (with Iris) and Forge (with Oculus)

Here's some crash reports :
- [fabric-crash-report.txt](https://github.com/user-attachments/files/15786525/crash-2024-06-11_12.27.03-client.txt)
- [forge-crash-report.txt](https://github.com/user-attachments/files/15786549/crash-2024-06-11_11.20.21-client.txt)

If necessary, i can provide reports from other players on the server i'm playing with.

Hope this helps!

**Comment by antdoesthings** [comment]
Same for me on forge 1.20.1 with this mod and like foxy's, mostly happens when shaders are off. 

It also seems to happen when I change a deployer's mode.

Here's a crash report from me:
[crash-2024-06-16_22.09.08-client.txt](https://github.com/user-attachments/files/15857925/crash-2024-06-16_22.09.08-client.txt)

Hope this helps!

**Comment by ERroooooR** [comment]
fabric 1.20.1
[crash-2024-06-22_16.53.32-client.txt](https://github.com/user-attachments/files/15936039/crash-2024-06-22_16.53.32-client.txt)
Hope this helps

**Comment by ZenithVal** [comment]
Can confirm
Fabric 1.20.1, only crashing when shaders are disabled.
[crash-2024-06-29_16.56.41-client.txt](https://github.com/user-attachments/files/16042188/crash-2024-06-29_16.56.41-client.txt)

**Comment by MoePus** [comment]
Any one try this?
Delete this line,
https://github.com/leon-o/iris-flw-compat/blob/6f8b46b2f0270fc5a7feea354dd2b03c96a295af/src/main/java/top/leonx/irisflw/mixin/MixinBufferBuilder.java#L38

Not having crashing issue for 1 hour.

**Comment by Rodrigo816** [comment]
This is a real problem, added this to my modpack and now I have tons of crash reports all related to this problem. This is very urgent.

**Comment by MoePus** [comment]
> This is a real problem, added this to my modpack and now I have tons of crash reports all related to this problem. This is very urgent.

[oculus-flywheel-compat-1.20.1-0.2.6.jar.zip](https://github.com/user-attachments/files/16391212/oculus-flywheel-compat-1.20.1-0.2.6.jar.zip)
```patch
@@ -31,13 +33,13 @@ public class MixinBufferBuilder implements BufferBuilderAccessor {
         extending = extending && BufferBuilderStateManager.isAllowExtend();
     }*/
 
     @ModifyVariable(method = "begin", at = @At("HEAD"), argsOnly = true)
     private VertexFormat iris$extendFormat(VertexFormat format) {
-        if(!BufferBuilderStateManager.isAllowExtend()){
+        if (!BufferBuilderStateManager.isAllowExtend()) {
             extending = false;
-            return DefaultVertexFormat.BLOCK;
+            if (IrisApi.getInstance().isShaderPackInUse())
+                return DefaultVertexFormat.BLOCK;
         }
-
         return format;
     }
 }
```

with this change made, i am not facing crashing issues for couples of weeks, 
you could try it

**Comment by Rodrigo816** [comment]
> > This is a real problem, added this to my modpack and now I have tons of crash reports all related to this problem. This is very urgent.
> 
> [oculus-flywheel-compat-1.20.1-0.2.6.jar.zip](https://github.com/user-attachments/files/16391212/oculus-flywheel-compat-1.20.1-0.2.6.jar.zip)
> 
> ```diff
> @@ -31,13 +33,13 @@ public class MixinBufferBuilder implements BufferBuilderAccessor {
>          extending = extending && BufferBuilderStateManager.isAllowExtend();
>      }*/
>  
>      @ModifyVariable(method = "begin", at = @At("HEAD"), argsOnly = true)
>      private VertexFormat iris$extendFormat(VertexFormat format) {
> -        if(!BufferBuilderStateManager.isAllowExtend()){
> +        if (!BufferBuilderStateManager.isAllowExtend()) {
>              extending = false;
> -            return DefaultVertexFormat.BLOCK;
> +            if (IrisApi.getInstance().isShaderPackInUse())
> +                return DefaultVertexFormat.BLOCK;
>          }
> -
>          return format;
>      }
>  }
> ```
> 
> with this change made, i am not facing crashing issues for couples of weeks, you could try it

Can you make a PR so the author publish the fix?

**Comment by MoePus** [comment]
@Rodrigo816 
Its just avoiding crashings instead of fixing the actual problem, so..
