### ISSUE TITLE
Rendering is broken for some reason (Forge 1.20.1) (For Oculus 1.7+)

### ISSUE THREAD

**Issue by Alexandqr** [leon-o/iris-flw-compat#128]
I don't know why but when adding this mod and running shaders, any animated create block is not rendered properly and instead leaves a glitchy mess around the screen. When shaders are disabled, the glitchyness disappears, but so do the animated parts of create blocks. This renders the game unplayable with this mod.

Here's a screenshot of what this looks like:
![2024-06-12_18 10 13](https://github.com/leon-o/iris-flw-compat/assets/72367464/704d7259-b776-4335-abe8-dd20748d85bf)

Here's the log output:
[latest.log](https://github.com/user-attachments/files/15812409/latest.log)

Here's a list of the mods used (put in images otherwise it would take too long):
![image](https://github.com/leon-o/iris-flw-compat/assets/72367464/cf6b1024-dce8-488d-8c93-a7245834d0fa)
![image](https://github.com/leon-o/iris-flw-compat/assets/72367464/e3e43d56-beb1-47ce-9f95-747e3e895732)
![image](https://github.com/leon-o/iris-flw-compat/assets/72367464/3608d61e-f258-4850-b4db-a9ee8d825bde)
![image](https://github.com/leon-o/iris-flw-compat/assets/72367464/29f26a68-d0f0-438e-8c5b-74c6831781ff)

If a fix could be figured out for this, that would be great :)

**Comment by jaygamer252** [comment]
This is Intresting since for me its actually the other way around 
![Screenshot (1)](https://github.com/user-attachments/assets/58037482-ebe1-4d43-bfdd-ca372ff31689)
![Screenshot (2)](https://github.com/user-attachments/assets/825d2871-e21e-4cb8-8803-7f2641d5d204)
And yes i tried every single option of the Flywheel Modes

**Comment by jaygamer252** [comment]
Update to this Issue by the way if it helps. It seems that this bug occurs for me only when joining a world with shaders already enabled cause, if I join without one enabled this bug doesn't happen at all, doesn't matter when I turn them on then or off.

**Comment by leon-o** [comment]
Try the latest version. If the issue still exists, you can re-open this issue again.
