### ISSUE TITLE
Some shadows on moving multiblock parts does not look right (Complementary v4)

### ISSUE THREAD

**Issue by shanoaice** [leon-o/iris-flw-compat#13]
![图片](https://user-images.githubusercontent.com/25174488/194677115-29aacb80-cbf8-4ffc-80e6-49aba8fee76f.png)

The color of Deployer should normally look like an yellowish-white, but with Complementary v4 enabled with this compat mod, its color turns into a brownish-black.

Forge version: 40.1.74
Iris (Oculus) version: 1.2.5a
Iris Flywheel Compat Version: 0.1.5-ALPHA

It seems like #9 is related too.

**Comment by leon-o** [comment]
Yes, this is a bug. There must be something wrong with the lightmap of moving blocks.

**Comment by leon-o** [comment]
This bug has been fixed in 0.1.7b.
