### ISSUE TITLE
Iris 1.6.11 compat

### ISSUE THREAD

**Issue by mikkerlo** [leon-o/iris-flw-compat#130]
It looks like Iris-Flw-compat apparently doesn't support iris 1.6.11 for minecraft 1.19.2 and I miserably failed to build it this way. To be more precise it's failing when running. Can somebody help me?

**Comment by king23333cao** [comment]
Is your situation the same as mine, with the Mojang interface progress bar loading repeatedly?

**Comment by leon-o** [comment]
Have you tried checking if the issue still occurs when not using the shaderpack?
