### ISSUE TITLE
Need help w Better Minecraft (forge)v28

### ISSUE THREAD

**Issue by Nozomibestgirl** [leon-o/iris-flw-compat#131]
When i try to open the game it crashes and the logs show this.I have installed some extra mods, like Optifine , Advanced combat,Fps increaser and Fps reducer +a resource pack and a shaderpack it it matters.
[message.txt](https://github.com/user-attachments/files/15913676/message.txt)

**Comment by leon-o** [comment]
[15:00:34] [main/ERROR]: Unsupported installed optional dependencies:
	Mod ID: 'curios', Requested by: 'quark', Expected range: '[5.6.1,)', Actual version: '5.3.5+1.20.1'
	
Update your curios to 5.6.1.
