### ISSUE TITLE
Active Mechanical Bearings with Active Components cause OpenGL Error spam in logs at thousands per minute

### ISSUE THREAD

**Issue by Barerock** [leon-o/iris-flw-compat#136]
Title. Seems to be random whether a world has this issue or not. I tested this gradually with a few hundred mods and one world has it and another doesn't, even with all mods active on the test world. Seems to be relatively harmless, so I'm just going to disable error logging for now. I flew around the test save of my survival and found that mechanical bearings specifically cause this, while other bearing types do not.

It's a generic OpenGL "god I'm not working right pay attention" error, so not much to share.

**Comment by Barerock** [comment]
Okay I tested this further, it so happens that what's causing the error is the activation of components, such as saw blades cutting wood (but fine if they're not). What really does it is mechanical harvesters, which instantly start outputting errors. This is a huge issue, and I'll test further to see if it's only on bearings (I think it is, I've tested gantry poles)

**Comment by Barerock** [comment]
Moving gantry carriages will actually make this error as well, even with no components attached.

**Comment by leon-o** [comment]
Thank you for reaching out! I need some additional information to locate the issue. Could you please provide the game version, mod version, and a list of all the mods you are currently using?

**Comment by Barerock** [comment]
I can't believe I didn't include these already, it's rote by now.
Create: 0.5.1f
iris flw: 1.0.0
Embeddium: 0.3.24
Oculus: 1.7.0
Forge 47.2.20
MC: 1.20.1

This does not occur with this base arrangement, so here's a full list of my Create addons and potential modifiers:

![image](https://github.com/user-attachments/assets/ce3ad96f-2b01-4043-b155-046ff7585ce8)
![image](https://github.com/user-attachments/assets/266ee8e6-6a86-459e-be9c-41ba9e1f5fa1)
![image](https://github.com/user-attachments/assets/84a17a9c-9371-4d56-a744-ec09576b26e5)
![image](https://github.com/user-attachments/assets/86a9aeee-dd5c-4581-bdd2-ff4c5e901e52)
![image](https://github.com/user-attachments/assets/ab94ecda-5c14-4bb3-adbb-3f75fc7d95ae)

I will test this list currently, and if the issue occurs I will batch test until it doesn't.

**Comment by Barerock** [comment]
SCRATCH ALL OF THAT

This occurs with the base arrangement. I just forgot that bearings don't do it on their own, it's the attached parts like mechanical harvesters, saws, gantries, etc when active.

So I'm going to delete that list.

**Comment by Barerock** [comment]
[latest.log](https://github.com/user-attachments/files/16422478/latest.log)

**Comment by leon-o** [comment]
![image](https://github.com/user-attachments/assets/fcfb84d4-976f-4ad8-8b3c-6fe5c16498e0)
I followed your instructions and did not reproduce the issue.

I noticed a error in the log you provided: 
```
0(451) : error C5041: cannot locate suitable resource to bind variable "at_midBlock". Possibly large array.
``` 

The related code is in shadow.glsl
```c
#if COLORED_LIGHTING > 0
    attribute vec3 at_midBlock;
#
``` 

I suspect it might be related to the GPU driver; the shader might be too complex, causing the GPU driver to fail to link. I tested it on my 4070ti and did not encounter this issue.

Currently, there is a way to avoid this problem: use another shaderpack or turn off the 'Advanced Color Lighting'.

![image](https://github.com/user-attachments/assets/c2c84d2a-9f47-4873-ad3f-9778e95774f6)

**Comment by Barerock** [comment]
Aw shucks, that's two things that are incompatible with ACL, though this seems like it's from Unbound's end, not the mod's. I'll let Emin know about this here thang.

**Comment by Barerock** [comment]
Shader devs say this is an issue with flywheel compat. Can't really say, because ACL is a known point of contention with compatibility. I've witnessed it have issues with several other seemingly unrelated rendering jobs.
