### ISSUE TITLE
Visual error with steam n rails mod.

### ISSUE THREAD

**Issue by ExpoTr** [leon-o/iris-flw-compat#137]
It is fixed with the /flywheel backend off command, but this completely loses the importance of this mod.This entity is constantly teleport to me.When you place a track from steam n rails mod it should appear.

version=1.20.1
Forge=47.2.0
Windows=10

Edit=I realized that "the factory must grow" addon may also be causing this problem

![Java-runtime-gamma Screenshot 2024 07 16 - 21 21 46 75](https://github.com/user-attachments/assets/4b4df3a6-258f-4d23-8e07-9c5dd36357df)

**Comment by leon-o** [comment]
Could you please provide the game version, mod version, and a list of all the mods you are currently using? With these details, I'll be able to help you more effectively. 😊

Additionally, I noticed that you are not using shaderpacks. This mod will not function properly unless shaderpacks are enabled. If you prefer not to use shaderpacks, you may consider removing this mod.
