### ISSUE TITLE
Visual Rendering bug with Iris and Oculus

### ISSUE THREAD

**Issue by TheMegaSad** [leon-o/iris-flw-compat#138]
There is a visual bug when using either Iris or Oculus when flywheel's backend is set to "batched" and shaders are enabled. The issue leaves once flywheel is set to instanced or turned off. This is only apparent when this mod is added. Entities also tend to "flicker". I have encountered this issue on both Fabric and Forge using the latest version. Only other thing I can think of is that I am using Nvidium and BSL Shaders (MC. 1.20.1).
![image](https://github.com/user-attachments/assets/77809e34-0a97-41ec-855d-a363eaa1cf8a)

**Comment by TheMegaSad** [comment]
Only other thing of note that I can think of is that I am using Nvidium

**Comment by leon-o** [comment]
Do not use "batched"; instead, use "Instanced". Batched is not supported, and Instanced has better performance. There is no reason to use Batched.
