### ISSUE TITLE
Support AstraLex Shader

### ISSUE THREAD

**Issue by shanoaice** [leon-o/iris-flw-compat#14]
AstraLex Shader is an edit of BSL Shader with great visual effect. Currently when using together with Iris & Oculus Flywheel Compat mod, all moving blocks from Create renders with incorrect color and model.

![image](https://user-images.githubusercontent.com/25174488/194759623-5cd9b336-efa6-4786-8a4f-bf62ac2f12c4.png)
![image](https://user-images.githubusercontent.com/25174488/194759636-2df003b7-d486-4c49-ae4e-48afd4895760.png)

**Comment by leon-o** [comment]
![image](https://user-images.githubusercontent.com/10016655/194762013-7561e4db-41bb-4520-9e73-bca1924ee759.png)

It works fine with AstraLex_(BSL_EDIT)_V64.0.
Can you provide more information about the version of AstraLex you use?

**Comment by shanoaice** [comment]
Very odd, a restart solves this issue and it never happened again. Might be a driver/Oculus glitch. Closing this.
