### ISSUE TITLE
Crashing with latest version

### ISSUE THREAD

**Issue by Barerock** [leon-o/iris-flw-compat#140]
[crash-2024-07-29_14.46.37-client.txt](https://github.com/user-attachments/files/16417869/crash-2024-07-29_14.46.37-client.txt)
[latest.log](https://github.com/user-attachments/files/16417866/latest.log)

Can't render camera?
Create, Embeddium, Flywheel compat, Oculus
1.20.1
Forge 47.2.20

**Comment by brisingraerowing** [comment]
The 1.1.0 JAR is a development JAR, not a release JAR. The development JAR needs to be excluded in the CI build script.

**Comment by Barerock** [comment]
Good to know, that is important.

**Comment by brisingraerowing** [comment]
A couple other mods have had this issue as well. I think (Neo)Forge Gradle changed something and added the new JAR.

**Comment by leon-o** [comment]
I'm sorry. The CI script uploaded the wrong JAR.

**Comment by Barerock** [comment]
> I'm sorry. The CI script uploaded the wrong JAR.

You're all good, mistakes happen <3

**Comment by L0stkid** [comment]
Sorry if my question is stupid, I have the same problem, forge, oculus, minecraft 1.20.1 and it crashes when I load the jar. What am I not taking into consideration?
