### ISSUE TITLE
Visual bug with shaders in the oculus + minecraft version 1.20.1

### ISSUE THREAD

**Issue by L0stkid** [leon-o/iris-flw-compat#142]
![2024-08-01_12 34 16](https://github.com/user-attachments/assets/7f986a77-3bf2-4a15-b0cb-1d33ebbd9872)

Has anyone had this problem?
When I load the .jar 1.1.0 with forge, oculus and minecraft 1.20.1 my gameplay looks like this when using the complementary shaders. The funny thing is that the performance improvement is noticeable, but half of my screen now looks black.

Do I have to use a specific version of shaders? I have tried other shaders and they all look the same, even when changing, it crashes many times.

**Comment by leon-o** [comment]
Could you please tell me which mods you have installed? Providing the log files may help me locate the issue more quickly.
