### ISSUE TITLE
Log spam with Euphoria Patches when entity shadows is enabled

### ISSUE THREAD

**Issue by ThatKatNaps** [leon-o/iris-flw-compat#143]
When using Euphoria Patches and Iris Flywheel Compat, and having the entity shadows enabled, the log gets spammed errors similar to the one below

OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. <program> object is not successfully linked, or is not a program object.'

I am aware of previous issues regarding compatibility between Euphoria Patches and Iris Flywheel Compat, and am submitting this issue to both boards

**Comment by GuyGieri** [comment]
Came here to report the same issue

https://mclo.gs/ZqJn5Ne

**Comment by leon-o** [comment]
There are duplicated issues: #136, #89. It should be fixed by commit 3d07f64.

**Comment by GuyGieri** [comment]
Hey man, Ive updated but the error persists for me
