### ISSUE TITLE
LabPBR dosnt work with Create: Copycats+ Cogs

### ISSUE THREAD

**Issue by CharlZ02** [leon-o/iris-flw-compat#145]
Setup: Minecraft 1.20.1 on Forge, Oculus Embeddium and Create: Copycats+ together with in Dev Bliss (when Pbr reflections are enabled) and Labpbr pack
Problem: CopyCat Cogs dosnt render properly in Bliss (and other shaders) 
![2024-08-06_11 12 00](https://github.com/user-attachments/assets/3a34b182-bda2-4bec-aa2b-d7124c6e5307)

Sorry for my first bug report I did yesterday about this problem didnt mean to send it. Hope you can fix those problems great mod btw :)
If you need more info let me know

**Comment by CharlZ02** [comment]
Also happend with BSL Shader when actvating advanced materials.
Happens to Both Cogwheels variants and Shaft but not to the fluidpipe of the mod

**Comment by leon-o** [comment]
It seems duplicated with #78。

**Comment by CharlZ02** [comment]
Oh that is  bad its the only thing that breaks with the shader (when disabling Pom). It even fixes a bug with contraption shadows.
So good work and good luck

**Comment by leon-o** [comment]
I'm really sorry, it seems that it's not the same issue as #125, it was my oversight.

**Comment by leon-o** [comment]
There is a relative issue:
- #78

**Comment by CharlZ02** [comment]
really no problem im just here to report. With the egotisticle reason that I want to include this mod in a modded valhelsia 6 Modpack and Im having 20fps compared to smooth 60 near my village without your mod.
anyways great work

**Comment by CharlZ02** [comment]
Oculus flywheel compat 1.1.2 didnt fix anything with bliss in my testing (as a quick follow-up)
