### ISSUE TITLE
[Crash // 1.18.2 - 1.0.2] Oculus/Iris Flywheel Compat requires a Non-existant Version of Flywheel

### ISSUE THREAD

**Issue by FocalFlare** [leon-o/iris-flw-compat#149]
_Recently I updated this mod to 1.0.2, and upon launching Minecraft, the game immediately crashes because I'm missing the correct version of Flywheel, which is to be expected. Knowing that, I went to look for version 0.6.9 of Flywheel and they have it available nowhere. [This issue on the Flywheel GitHub](https://github.com/Engine-Room/Flywheel/issues/205) also mentions this issue, but it's closed with the suggestion of removing Create, which doesn't work for this issue since I don't play with Create._

_I know that Flywheel has been made an optional mod for some mods and a required mod for the rest--therefore calling it legacy, but please let me know if this specific issue is on the side of this mod or Flywheel._

_Solutions for this crash might work for everyone who's having this same issue but are 100% not guaranteed to work for those with even a slightly different issue. Regardless, I appreciate your input(s)!_

### Version Info
- Minecraft 1.18.2
- Forge 40.2.21
- Flywheel 0.6.8a
- Oculus Flywheel Compat 1.0.2

### Steps to Reproduce
1. Update this mod to this version.
2. Have any version of Flywheel before 0.6.9.
3. Expect 0.6.9 to exist.

### Behaviors
- Expected: Launch my game like normal.
- Actual: Crash my game due to a wrong-version mod dependency exception.

### What I Tried
- Disable Flywheel (crashes my game due to a missing mod dependency exception).

### Crash Log(s)
[crash-2024-08-09_22.09.42-client.txt](https://github.com/user-attachments/files/16568299/crash-2024-08-09_22.09.42-client.txt)

### Relevant Info
The crash log shows that I'm missing v0.6.9 of Flywheel:
![image](https://github.com/user-attachments/assets/12cc7cc4-3539-4d36-9276-f575cdf7428f)

Me trying to look for said version only for it to not be available:
![image](https://github.com/user-attachments/assets/0437e396-c9b6-4c7a-aa90-62b34170f0e0)

**Comment by leon-o** [comment]
You can download it from this [website](https://[maven.tterrag.com/com/jozufozu/flywheel/flywheel-forge-1.18.2/](https://maven.tterrag.com/com/jozufozu/flywheel/flywheel-forge-1.18.2/)).

**Comment by leon-o** [comment]
The latest version includes Flywheel in the jar, so you don't need to install it separately now.

**Comment by FocalFlare** [comment]
That seemed to have fixed it. 🖤

_**This issue has been solved, but for anyone who's having the same issue and can't access the link:**_ _**https://maven.tterrag.com/com/jozufozu/flywheel/flywheel-forge-1.18.2/**_
