### ISSUE TITLE
Seus PTGI HRR 3 and 2.1 having rendering errors while using create mod  + Oculus flywheel compat

### ISSUE THREAD

**Issue by KurAlis** [leon-o/iris-flw-compat#150]
I am trying to use **sues ptgi hrr 3 or 2.1** and they are having **weird rendering errors**, i thought that this was fixed...  if there is a way it can be fixed by a setting or using another compatibility mod let me know...  (info : Minecraft 1.20.1 forge 47.3.0, embiddium + oculus + oculus/iris flywheel compat )

![image](https://github.com/user-attachments/assets/9f4138ff-bd8d-4694-b09a-3a01beffb71d)

**Comment by leon-o** [comment]
Fixed in 2ae07d5.
