### ISSUE TITLE
与immediatelyfast和EBE不兼容

### ISSUE THREAD

**Issue by masonclomid** [leon-o/iris-flw-compat#153]
我在用forge 1.20.1的
oculus-flywheel-compat-forge1.20.1+1.1.3
embeddium-0.3.30
Oculus m1.20.1-1.7.0
enhancedblockentities-0.9 (信雅互联)
immediatelyfast-1.2.20

instancing引擎下与immediatelyfast共用时，
1、看向空矿车、动力矿车、漏斗矿车时gpu占用飙升
![Fastbug](https://github.com/user-attachments/assets/f01cdea3-0d31-4f16-a44a-46387fd6f27d)
但除三者尤其是前两者外其他矿车，哪怕是别的模组的矿车都没这情况，同时batching引擎下所有实体和块实体都不渲染直到这三种矿车被放置。

2、粒子在视角移动时会像被粘走一样随屏幕平移，有时还会在屏幕上渲染背后看不到的粒子。
![Fastbug2](https://github.com/user-attachments/assets/315229c5-fb3d-4c49-90c9-f4431cfa51ca)

另外与enhancedblockentities(EBE)共用时，原版箱子的表面会有类似z抖动的闪烁，截图截不出来。(矿车也有高占用但没前者那么严重)
关引擎后一切问题排除。以上都经过控制变量单独测试得到。

**Comment by leon-o** [comment]
去掉oculus-flywheel-compat后是否还有这些问题?
看你的游戏截图中并没有使用光影，oculus-flywheel-compat事实上并没有启用。

**Comment by masonclomid** [comment]
去掉ofc就没有问题了。这么说来这两个mod应该是和内置的flywheel不兼容，现在是没加create的，我之后单独和create测试对比下。请问可以建议一下如果flywheel和immediatelyfast、EBE不能共用的话留哪个更好吗？

**Comment by leon-o** [comment]
如果你用Create的话，Flywheel是少不了的。Create自带了Flywheel，你没办法不装。

**Comment by masonclomid** [comment]
最近immediatelyfast和飞轮更新之后矿车问题好像解决了，期待大佬早日跟进飞轮啊，EBE还是不兼容instancing引擎但无关紧要了。
