### ISSUE TITLE
"Flywheel isn't Flywheeling"

### ISSUE THREAD

**Issue by PredoAgudo** [leon-o/iris-flw-compat#154]
If I look in the direction of the water wheels, not looking directly at them, just looking in the direction, whether it is above or below my view, it always stays at 38 fps, I've already changed the backend, I switched between the three instances, no did nothing

**Comment by leon-o** [comment]
It seems that you should consistently use the 'Instanced' backend for optimal performance. If the FPS is not increasing as expected, it could be an indication of a GPU bottleneck.
