### ISSUE TITLE
update the mod to a new version of the flywheel (0.6.11-13)

### ISSUE THREAD

**Issue by Smeorkuk** [leon-o/iris-flw-compat#158]
your mod has too old version of flywheel(0.6.11-13)
create(v0.5.1g)
please update

**Comment by Smeorkuk** [comment]
![изображение](https://github.com/user-attachments/assets/24f717f6-10bb-47f8-9954-5dfe6f8d0e5c)
https://mclo.gs/S5znNpi here is the log

**Comment by mlus-asuka** [comment]
shouldn't have jarjar in mod file at all

**Comment by leon-o** [comment]
> shouldn't have jarjar in mod file at all

You're right. I removed it.
