### ISSUE TITLE
Support for Iris (not Oculus) on Forge?

### ISSUE THREAD

**Issue by SlimF** [leon-o/iris-flw-compat#167]
Posted earlier by mistake, apologies.

My question is if it's possible to add support for Iris on Forge. There is a beta build that could be found in the #unstable-releases channel on the Iris server.
[Link](https://discord.gg/the-iris-project-774352792659820594)

**Comment by leon-o** [comment]
Yes, I will add support for Iris on Forge when the stable version are released.
