### ISSUE TITLE
Flywheel compat crashes latest oculus build based on 1.7.5 Iris

### ISSUE THREAD

**Issue by baseb01** [leon-o/iris-flw-compat#171]
Oculus recently pushed to github a version of their mod with 2.2 Distant Horizons support and unfortunately flywheel compat crashes the game when you try to turn shaders on.

**Comment by Billnotic** [comment]
In my case the game crashes even before entering the main menu when using the latest oculus build from the github.

**Comment by TheRealMagicSeal** [comment]
Author published fix for Fabric but not for forge. Here's a temp fix for it : https://github.com/TheRealMagicSeal/iris-flw-compat/releases

**Comment by NoMoreStars** [comment]
Yup, can confirm this is still happening with the latest version of Oculus and Distant Horizons, I have a [crash log](https://mclo.gs/JuO2TtG) with more details.
