### ISSUE TITLE
Flywheel embeded in "create mod" compatibility with rubidium

### ISSUE THREAD

**Issue by phooenixdassmatte** [leon-o/iris-flw-compat#175]
I may be saying things wrong but this was a headache to find haha.

Flywheel imbedded in create apperently needs sodium 0.6.0-beta.2 or above

Our server uses forge modloader so i need to use oculus rubidium instead and i've tried all of the versions of rubidium but i still get a prompt that the flywheel mod can't detect sodium. And I've double, tripple and quadruple checked the mod folder and deleted cache and config folders.

So there seems to be failure to detect rubidium by the flywheel mod inside the create mod, i think?

So my setup is: 
Mc 1.20.1
Oculus 1.7.0 for 1.20.1
rubidium 0.7.1a (okey i just checked at the date and it seems to be a little outdated compared to other mods, maybe?)

I also downloaded oculus flywheel compat version 1.1.2 hoping that it would override the flywheel mod in the create mod but that doesnt seem to happen. And i asked chat gpt if i could open up the create .jar and delete the flywheel mod but apperently it is nested heavily into the create mod? 

Seems to always be in a wierd moment 22 situation, i shot down 2 other similar problems just to end up with new ones haha.

**Comment by Poopooracoocoo** [comment]
You should be using Embeddium instead of Rubidium.

**Comment by phooenixdassmatte** [comment]
> You should be using Embeddium instead of Rubidium.

Haha okey, ahh all these mods.

**Comment by phooenixdassmatte** [comment]
I'm sorry i forgot to say what i was ultimately trying to do.

I wanted to have this shader together with the create mods:
https://modrinth.com/shader/complementary-reimagined

But it doesn't seem to work. The game posts now atleast.
But Iris doesn't seem to work (required for shaders) because i don't see any shader options in video settings.
I have used optifine all my shaders playthroughs before but that doesn't seem to work here, or i'm just stupid. But this is kind of OT for you, outside of your mod.

**Comment by Poopooracoocoo** [comment]
> But this is kind of OT for you, outside of your mod

Sorry, I know I'm not the author of this mod but I'd like to add some things:

> But Iris doesn't seem to work (required for shaders) because i don't see any shader options in video settings.

Don't you mean Oculus? Oculus is a fork of Iris for Forge. Iris is a Fabric mod.

The following setup works for me:
Minecraft 1.20.1
Forge 47.3.11
Create 0.5.1.j
Embeddium 0.3.31
Oculus 1.7.0
Iris/Oculus Flywheel Compat 1.1.3b
Complementary 5.3

**Comment by phooenixdassmatte** [comment]
We moved over everything to a fabric environment instead and made a new modpack but with the fabric port of the create suite, and seems to work now.
