### ISSUE TITLE
1.19.2 Random crashes while flywheel backend is on

### ISSUE THREAD

**Issue by LuckySkye13** [leon-o/iris-flw-compat#19]
I'm experiencing random crashing to desktop when playing with Create, Oculus with Complementary Shaders, and this mod, among others. It doesn't generate a crash file, The timing seems fairly random, ranging from less than a minute to over an hour. Turning flywheel backend off makes the crashes stop, but halves my FPS... 

I listed all the mods I'm using at the bottom.

Looking through the instance folder, there's a file that appears to be a debug log? Here's some of it, I don't want to paste the whole thing since it seems to have identifiable info in it:

------------------------------------------

A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffbd1bf29c3, pid=12320, tid=21932
#
# JRE version: Java(TM) SE Runtime Environment (17.0.5+9) (build 17.0.5+9-LTS-191)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (17.0.5+9-LTS-191, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [nvoglv64.dll+0x14d29c3]

-------------------------------------------------------------

Current thread (0x0000020b1b865d90):  JavaThread "Render thread" [_thread_in_native, id=21932, stack(0x0000003078b00000,0x0000003078c00000)]

Stack: [0x0000003078b00000,0x0000003078c00000],  sp=0x0000003078bfdc50,  free space=1015k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [nvoglv64.dll+0x14d29c3]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 22397  org.lwjgl.opengl.GL11C.nglDrawElements(IIIJ)V org.lwjgl.opengl@3.3.1+7 (0 bytes) @ 0x0000020b2b9ecaf6 [0x0000020b2b9ecaa0+0x0000000000000056]
J 29161 c2 com.mojang.blaze3d.vertex.VertexBuffer.m_166882_()V minecraft@1.19.2 (22 bytes) @ 0x0000020b2c092ea4 [0x0000020b2c092e20+0x0000000000000084]
J 68153 c2 com.mojang.blaze3d.vertex.VertexBuffer.m_166876_(Lcom/mojang/math/Matrix4f;Lcom/mojang/math/Matrix4f;Lnet/minecraft/client/renderer/ShaderInstance;)V minecraft@1.19.2 (296 bytes) @ 0x0000020b2e199de0 [0x0000020b2e199280+0x0000000000000b60]
J 69996 c2 com.mojang.blaze3d.vertex.Tesselator.m_85914_()V minecraft@1.19.2 (11 bytes) @ 0x0000020b2c0e639c [0x0000020b2c0e6040+0x000000000000035c]
J 74782 c2 net.minecraft.client.particle.ParticleRenderType$2.m_6294_(Lcom/mojang/blaze3d/vertex/Tesselator;)V minecraft@1.19.2 (5 bytes) @ 0x0000020b2e50b05c [0x0000020b2e50b020+0x000000000000003c]
J 71156 c2 net.minecraft.client.particle.ParticleEngine.render(Lcom/mojang/blaze3d/vertex/PoseStack;Lnet/minecraft/client/renderer/MultiBufferSource$BufferSource;Lnet/minecraft/client/renderer/LightTexture;Lnet/minecraft/client/Camera;FLnet/minecraft/client/renderer/culling/Frustum;)V minecraft@1.19.2 (408 bytes) @ 0x0000020b2e77ffc8 [0x0000020b2e77e620+0x00000000000019a8]
J 75051 c2 net.minecraft.client.renderer.LevelRenderer.handler$bai000$iris$renderOpaqueParticles(Lcom/mojang/blaze3d/vertex/PoseStack;FJZLnet/minecraft/client/Camera;Lnet/minecraft/client/renderer/GameRenderer;Lnet/minecraft/client/renderer/LightTexture;Lcom/mojang/math/Matrix4f;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V minecraft@1.19.2 (135 bytes) @ 0x0000020b2ed3fe14 [0x0000020b2ed3fce0+0x0000000000000134]
J 71839 c2 net.minecraft.client.renderer.LevelRenderer.m_109599_(Lcom/mojang/blaze3d/vertex/PoseStack;FJZLnet/minecraft/client/Camera;Lnet/minecraft/client/renderer/GameRenderer;Lnet/minecraft/client/renderer/LightTexture;Lcom/mojang/math/Matrix4f;)V minecraft@1.19.2 (4235 bytes) @ 0x0000020b2e88682c [0x0000020b2e884100+0x000000000000272c]
J 74993 c2 net.minecraft.client.renderer.GameRenderer.m_109089_(FJLcom/mojang/blaze3d/vertex/PoseStack;)V minecraft@1.19.2 (744 bytes) @ 0x0000020b2ed1f094 [0x0000020b2ed1cca0+0x00000000000023f4]
J 74442 c2 net.minecraft.client.renderer.GameRenderer.m_109093_(FJZ)V minecraft@1.19.2 (885 bytes) @ 0x0000020b2ec05048 [0x0000020b2ec04a00+0x0000000000000648]
J 75245 c2 net.minecraft.client.Minecraft.m_91383_(Z)V minecraft@1.19.2 (1221 bytes) @ 0x0000020b2edf1e74 [0x0000020b2edf0600+0x0000000000001874]
j  net.minecraft.client.Minecraft.m_91374_()V+206 minecraft@1.19.2
j  net.minecraft.client.main.Main.m_239872_([Ljava/lang/String;Z)V+1488 minecraft@1.19.2
j  net.minecraft.client.main.Main.main([Ljava/lang/String;)V+39 minecraft@1.19.2
v  ~StubRoutines::call_stub
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0 java.base@17.0.5
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+133 java.base@17.0.5
j  jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+6 java.base@17.0.5
j  java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+59 java.base@17.0.5
j  net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(Ljava/lang/ModuleLayer;[Ljava/lang/String;)V+40 fmlloader@1.19.2-43.1.47
j  net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler$$Lambda$885+0x0000000800ff0740.run()V+8 fmlloader@1.19.2-43.1.47
j  cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch([Ljava/lang/String;Ljava/lang/ModuleLayer;)V+11 cpw.mods.modlauncher@10.0.8
j  cpw.mods.modlauncher.LaunchServiceHandler.launch(Ljava/lang/String;[Ljava/lang/String;Ljava/lang/ModuleLayer;Lcpw/mods/modlauncher/TransformingClassLoader;Lcpw/mods/modlauncher/LaunchPluginHandler;)V+58 cpw.mods.modlauncher@10.0.8
j  cpw.mods.modlauncher.LaunchServiceHandler.launch(Lcpw/mods/modlauncher/ArgumentHandler;Ljava/lang/ModuleLayer;Lcpw/mods/modlauncher/TransformingClassLoader;Lcpw/mods/modlauncher/LaunchPluginHandler;)V+21 cpw.mods.modlauncher@10.0.8
j  cpw.mods.modlauncher.Launcher.run([Ljava/lang/String;)V+310 cpw.mods.modlauncher@10.0.8
j  cpw.mods.modlauncher.Launcher.main([Ljava/lang/String;)V+78 cpw.mods.modlauncher@10.0.8
j  cpw.mods.modlauncher.BootstrapLaunchConsumer.accept([Ljava/lang/String;)V+1 cpw.mods.modlauncher@10.0.8
j  cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(Ljava/lang/Object;)V+5 cpw.mods.modlauncher@10.0.8
j  cpw.mods.bootstraplauncher.BootstrapLauncher.main([Ljava/lang/String;)V+515 cpw.mods.bootstraplauncher@1.1.2
v  ~StubRoutines::call_stub

siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0x0000000000000000

----------------------------------------------------

AdChimneys-1.19.2-9.1.6.0-build.0629.jar
alexsmobs-1.20.2.jar
Apotheosis-1.19.2-6.0.1.jar
appleskin-forge-mc1.19-2.4.2.jar
architectury-6.3.49-forge.jar
ars_creo-1.19.2-3.1.0.jar
ars_elemental-1.19.2-0.5.5.6.jar
ars_instrumentum-1.19.2-3.2.0.jar
ars_nouveau-1.19.2-3.4.6.jar
artifacts-1.19.2-5.0.1.jar
AutoRegLib-1.8-54.jar
balm-4.5.3.jar
bettercombat-forge-1.4.5+1.19.jar
Beyond-Earth-1.19.2-6.3.jar
BiomesOPlenty-1.19.2-17.1.1.162.jar
blockui-1.19-0.0.64-ALPHA.jar
blue_skies-1.19.2-1.3.20.jar
blueprint-1.19.2-6.1.0.jar
Bookshelf-Forge-1.19.2-16.1.11.jar
BorderlessWindow-1.19.1-1.5.2.jar
BotanyPots-Forge-1.19.2-9.0.11.jar
BotanyPotsTiers-Forge-1.19.2-3.1.0.jar
BotanyTrees-Forge-1.19.2-5.0.1.jar
bwncr-forge-1.19.2-3.14.0.jar
caelus-forge-1.19.2-3.0.0.6.jar
car-1.19.2-1.0.0.jar
cardboardboxes-1.19-0.0.6.jar
cfm-7.0.0-pre34-1.19.jar
chococraft-1.19.2-0.5.2.jar
citadel-2.0.0-1.19.jar
client-1.19.2-20220805.130853-srg.jar
cloth-config-8.2.88-forge.jar
CodeChickenLib-1.19.2-4.3.0.470-universal.jar
configured-2.0.1-1.19.2.jar
Controlling-forge-1.19.2-10.0+7.jar
cookingforblockheads-forge-1.19.2-13.3.0.jar
CosmeticArmorReworked-1.19.2-v1a.jar
craftingtweaks-forge-1.19-15.1.0.jar
crashutilities-6.1.jar
create_connected_blocks-0.5.3.jar
create_crystal_clear-0.1e-1.19.2.jar
create_dragon_lib-1.19.2-1.1.1.jar
create_enchantment_industry-1.19.2-for-create-0.5.\|Create
create_jetpack-2.1.0.jar
create_mechanical_extruder-1.19.2-1.3.0.jar
create_misc_and_things_1.19.2_1.1B.jar
create-1.19.2-0.5.0.f.jar
createaddition-1.19.2-20221103a.jar
createcafe-1.0.0-1.19.2.jar
createchunkloading-1.3.0-forge.jar
create-confectionery1.19.2_v1.0.8.jar
createdeco-1.2.11-1.19.2.jar
createoreexcavation-1.19-0.3.1.jar
createplus-1.19.2_v0.5.2a.jar
createsifter-1.19.2-1.2.3.f.jar
create-stuff-additions1.19.2_v2.0.1c.jar
curios-forge-1.19.2-5.1.1.0.jar
Cyclic-1.19.2-1.7.12.jar
CyclopsCore-1.19.2-1.17.0.jar
Decorative
deeperdarker-forge-1.1.3-forge.jar
dimdungeons-168-forge-1.19.0.jar
DoggyTalentsNext-1.19.2-1.1.0.jar
domum_ornamentum-1.19-1.0.67-ALPHA-universal.jar
elytraslot-forge-6.0.0+1.19.2.jar
EnchantmentDescriptions-Forge-1.19.2-13.0.3.jar
EnderStorage-1.19.2-2.10.1.181-universal.jar
engineersdecor-1.19.2-forge-1.3.26.jar
entityculling-forge-1.5.2-mc1.19.1.jar
EvilCraft-1.19.2-1.2.9.jar
expandability-forge-7.0.0.jar
experienceobelisk-v1.3.6-1.19.2.jar
ExplorersCompass-1.19.2-1.3.0-forge.jar
extendedflywheels-1.2.2-1.19.2-0.5.f.jar
extragolems-19.2.4.jar
Fallingleaves-1.19.1-1.3.0.jar
farmingforblockheads-forge-1.19-11.1.0.jar
FastLeafDecay-30.jar
flywheel-forge-1.19.2-0.6.7-8.jar
forbidden_arcanus-1.19.2-2.1.0-beta2.jar
forge-1.19.2-43.1.47-universal.jar
ForgeEndertech-1.19.2-10.0.5.0-build.0599.jar
geckolib-forge-1.19-3.1.36.jar
globalxp-1.19-1.10.2.jar
goblintraders-1.8.0-1.19.2.jar
HealthOverlay-1.19.2-7.1.1.jar
ImmersiveEngineering-1.19.2-9.0.0-153.jar
industrial-foregoing-1.19.2-3.3.2.0-2.jar
inventorysorter-1.19.2-21.0.4.jar
jei-1.19.2-forge-11.4.0.284.jar
jeimultiblocks-1.19.2-0.0.3.jar
journeymap-1.19.1-5.9.0beta2-forge.jar
JustEnoughProfessions-forge-1.19-2.0.1.jar
JustEnoughResources-1.19.2-1.1.1.184.jar
Kiwi-1.19.1-forge-8.1.3.jar
laserio-1.5.1.jar
lootr-1.19-0.3.20.57.jar
lostcities-1.19-6.0.8.jar
macawsbridgesbop-1.19.2-1.0.jar
macawsroofsbop-1.19.2-1.2.jar
mahoutsukai-1.19.2-v1.34.35.jar
mcw-bridges-2.0.5-mc1.19.2forge.jar
mcw-doors-1.0.7-mc1.19.2.jar
mcw-fences-1.0.6-mc1.19.2.jar
mcwfencesbop-1.19.2-1.0.jar
mcw-furniture-3.0.2-mc1.19.2.jar
mcwfurnituresbop-1.19.2-1.1.jar
mcw-lights-1.0.4-mc1.19.2.jar
mcw-paintings-1.0.4-mc1.19.2.jar
mcw-paths-1.0.1-mc1.19.2.jar
mcw-roofs-2.2.1-mc1.19.2-forge.jar
mcw-trapdoors-1.0.7-mc1.19.2.jar
Mekanism-1.19.2-10.3.5.473.jar
MekanismAdditions-1.19.2-10.3.5.473.jar
MekanismGenerators-1.19.2-10.3.5.473.jar
MekanismTools-1.19.2-10.3.5.473.jar
minecolonies-1.19.2-1.0.1094-ALPHA.jar
minecraft-comes-alive-7.3.21+1.19.2-universal.jar
mob_grinding_utils-1.19.2-0.4.46.jar
MobCatcher-Forge-1.19.2-1.2.11.jar
moonlight-1.19.2-2.1.4-forge.jar
moredragoneggs-3.2.jar
MoreMekanismProcessing-1.19.2-3.0.jar
MouseTweaks-forge-mc1.19-2.23.jar
multi-piston-1.19.2-1.2.19-ALPHA.jar
NaturesCompass-1.19.2-1.9.7-forge.jar
notenoughanimations-forge-1.6.2-mc1.19.2.jar
notenoughcrashes-4.1.8+1.19.2-forge.jar
oculus-flywheel-compat-1.19.2-0.1.6-ALPHA.jar
oculus-mc1.19.2-1.2.8.jar
OreExcavation-1.11.166.jar
overloadedarmorbar-1.19.2-7.jar
paragon-forge-1.0.3b-1.19x.jar
Patchouli-1.19.2-77.jar
personality-1.19-3.0.1.jar
Placebo-1.19.2-7.0.1.jar
player-animation-lib-forge-0.3.5.jar
pneumaticcraft-repressurized-1.19.2-4.1.2-9.jar
polylib-forge-1900.0.2-build.27.jar
polymorph-forge-0.45.0+1.19.2.jar
PuzzlesLib-v4.3.12-1.19.2-Forge.jar
Quark-3.3-371.jar
QuarkOddities-1.18.jar
Rex's-AdditionalStructures-1.19.x-(v.4.0.2).jar
rubidium-0.6.2.jar
SilentCompat-forge-1.19.2-1.0.0.2.jar
silent-gear-1.19.2-3.0.5.jar
silent-lib-1.19.2-7.0.3.jar
silents-gems-1.19.2-4.4.0.jar
simpleplanes-1.19.2-5.0.3.jar
SimpleStorageNetwork-1.19-1.6.4.jar
simplylight-1.19.2-1.4.5-build.42.jar
SnowRealMagic-1.19.2-forge-5.0.3.jar
snowundertrees-1.19.2-1.3.jar
sophisticatedbackpacks-1.19.2-3.18.29.719.jar
sophisticatedcore-1.19.2-0.5.15.142.jar
soulshards-1.19-1.3.3.jar
structure_gel-1.19.2-2.7.1.jar
structurize-1.19.2-1.0.459-ALPHA.jar
supplementaries-1.19.2-2.2.13.jar
swingthroughgrass-1.19.2-1.10.0.jar
TerraBlender-forge-1.19.2-2.0.1.128.jar
The_Undergarden-1.19.2-0.8.3.jar
theoneprobe-1.19-6.2.2.jar
titanium-1.19.2-3.7.0-23.jar
ToastControl-1.19.2-7.0.0.jar
toomanyglyphs-1.19.2-2.2.45.12185.jar
Towns-and-Towers-1.19.2-1.9.jar
twilightforest-1.19-4.2.1421-universal.jar
UniversalEnchants-v4.2.8-1.19.2-Forge.jar
valhelsia_core-forge-1.19.2-0.4.0.jar
Waddles-1.19-0.9.1.jar
walljump-unofficial-1.5.3.5-all+1.19.2.jar
waystones-forge-1.19-11.1.0.jar
WitherSkeletonTweaks-1.19.2-8.0.0.jar
YungsApi-1.19.2-Forge-3.8.2.jar
YungsBetterDesertTemples-1.19.2-Forge-2.2.1.jar
YungsBetterDungeons-1.19.2-Forge-3.2.1.jar
YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar
YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar
YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar
YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar
YungsExtras-1.19.2-Forge-3.1.0.jar
grappling_hook_mod-1.19.2-1.19.2-v13.jar

**Comment by DRweidoGH** [comment]
I had the same issue until I removed immersive engineering

**Comment by leon-o** [comment]
It seems to be the same issue as #125, which has already been fixed.
