### ISSUE TITLE
1.18.2 Crash with new Oculus version

### ISSUE THREAD

**Issue by Brickmaster1** [leon-o/iris-flw-compat#23]
Minecraft: 1.18.2

Rubidium: 0.5.4

Oculus: 1.4.3

Logs: 
[latest.log](https://github.com/leon-o/iris-flw-compat/files/10127568/latest.log)

**Comment by leon-o** [comment]
Thanks for your feedback. This issue has been fixed. Please try the version of 0.1.8.
