### ISSUE TITLE
Game crashes with newest ocolus version. 1.18.2

### ISSUE THREAD

**Issue by IvorAmlug** [leon-o/iris-flw-compat#24]
Oculus 1.4.3
Flyhwheel 0.6.5
Flywheel compat 0.1.7 beta
rubidium 0.5.4
Forge 40.1.86
The issue always comes up when trying to lauch the game.
I know there allready been a report for this same issue i think. But his log had a lot of mods in it that are not required to reproduce it.
[crash-2022-12-02_00.45.00-client.txt](https://github.com/leon-o/iris-flw-compat/files/10136989/crash-2022-12-02_00.45.00-client.txt)
If u dont wanna download anything here is a pastebin:
https://pastebin.com/M9gfEFgZ

**Comment by leon-o** [comment]
Thanks for your feedback. This issue has been fixed. Please try the version of 0.1.8.
