### ISSUE TITLE
Game crashes when applying shader with oculus 1.4.3 and oculus-flywheel-compat 0.1.7

### ISSUE THREAD

**Issue by DRweidoGH** [leon-o/iris-flw-compat#25]
Minecraft loads up just fine but then I load into a world and apply shaders it crashes to the launcher and I cant launch the instance again

Works again when I either: 
 1. Remove Oculus-Flywheel Compat
 2. Downgrade Oculus to version 1.2.5a

Minecraft version: 1.18.2
Forge version: 40.1.86

Tested Forge versions with the same issue
- Forge 40.1.85
- Forge 40.1.84

Mods List:
create-1.18.2-0.5.0.e
flywheel-forge-1.18.2-0.6.5
oculus-1.4.3
oculus-flywheel-compat-1.18.2-0.1.7-BETA
rubidium-0.5.4

Crash report: [crash-2022-12-08_17.10.06-client.txt](https://github.com/leon-o/iris-flw-compat/files/10190763/crash-2022-12-08_17.10.06-client.txt) or https://pastebin.com/aP4kvFgR

**Comment by leon-o** [comment]
Thanks for your feedback. This issue has been fixed. Please try the version of 0.1.8.
