### ISSUE TITLE
Conflict with Flywheel Version 0.6.8+

### ISSUE THREAD

**Issue by afloofflam** [leon-o/iris-flw-compat#27]
During game load this mod conflicts with the current version of Flywheel, which is 0.6.8-13. It's requesting Flywheel 0.6.7 or above, and below 0.6.8. I'm currently using Oculus on Forge in Minecraft version 1.19.2 in order to use shaders. My version of Forge is 43.2.3.

**Comment by leon-o** [comment]
I have fixed it and uploaded it to curseforge. The version number is still 0.1.6 because there are no other changes. I hope you enjoy using it and let me know if you encounter any issues.

**Comment by afloofflam** [comment]
Thank you for working on this!
