### ISSUE TITLE
[Forge][1.19.2] Mod asks for flywheel version 0.6.7, when 0.6.7 is not available

### ISSUE THREAD

**Issue by Nayoh7467** [leon-o/iris-flw-compat#32]
![IrisFlywheelCompatIssue](https://user-images.githubusercontent.com/85239149/215361930-c702b2e9-bda4-41db-b570-be01a22bb936.JPG)

**Comment by Bellegas** [comment]
I am also experiencing the same issue.

**Comment by Bellegas** [comment]
I am also experiencing this issue.

**Comment by Bellegas** [comment]
Update: You can bypass this error by removing the dependency from the mods.toml file. Mod seems to work fine from there, at least so far. If you need me to explain further, just ask.

**Comment by Jehree** [comment]
> Update: You can bypass this error by removing the dependency from the mods.toml file. Mod seems to work fine from there, at least so far. If you need me to explain further, just ask.

Can you elaborate? I am having this exact issue but I can't seem to find a mods.toml file in my installation folders.

**Comment by Bellegas** [comment]
> > Update: You can bypass this error by removing the dependency from the mods.toml file. Mod seems to work fine from there, at least so far. If you need me to explain further, just ask.
> 
> Can you elaborate? I am having this exact issue but I can't seem to find a mods.toml file in my installation folders.

In order to make things as clear as I can I did it over again with pictures of the process, let me know if your still confused.

![snip](https://user-images.githubusercontent.com/38391170/221766830-90f14edf-f9a4-495b-a249-f251d1732fdb.PNG)
![snip2](https://user-images.githubusercontent.com/38391170/221766813-e650cd99-80b9-4341-8d07-fb69268f3541.PNG)

**Comment by Jehree** [comment]
That did the trick! Thanks so much for your help :)

**Comment by leon-o** [comment]
My mistake. I have fixed it and uploaded it to curseforge. The version number is still 0.1.6 because there are no other changes.
