### ISSUE TITLE
Crashes on Startup with 1.19.2

### ISSUE THREAD

**Issue by ItsJustDance** [leon-o/iris-flw-compat#34]
Can't even start up the game, crashes before anything can happen. 
Here's the crash report
[crash-2023-02-02_18.50.08-client.txt](https://github.com/leon-o/iris-flw-compat/files/10574891/crash-2023-02-02_18.50.08-client.txt)

**Comment by leon-o** [comment]
Sorry, I've been busy lately. You can download the latest version from curseforge.
