### ISSUE TITLE
Visual Bugs -1.19 alpha

### ISSUE THREAD

**Issue by PapaDimitri** [leon-o/iris-flw-compat#37]
Have been using 1.19 alpha version for forge and wierd visual bugs occur as seen on screenshots
![2023-03-05_13 25 25](https://user-images.githubusercontent.com/127027659/222960613-7ca0e141-c81c-4e39-8847-b00336b41dc8.png)

![2023-03-05_13 25 21](https://user-images.githubusercontent.com/127027659/222960610-a85740a7-bfe0-412a-af63-761365632745.png)
Also there is rendering problems with create things like cogwheels. While not using any shaderpack UI breakes

**Comment by JesseChin** [comment]
I am also getting similar visual bugs on Forge. Curiously, the mod actually works properly at 89 FOV. I am running Complementary Reimagined shaders at 55 FPS, which is quite amazing! 
![2023-03-21_20 50 31](https://user-images.githubusercontent.com/17260111/226773885-5f7c4892-ad96-42ee-a838-dfa53675d973.png)

At 90 FOV and greater, I start to get visual glitches.
![2023-03-21_20 50 40](https://user-images.githubusercontent.com/17260111/226774334-0df7d129-91a4-4d05-b1a6-cba82d1f1723.png)

It's perfectly playable disabling the FOV distortion effects and using 89 FOV, which is fine to play with. 

Using version 1.19.2-0.1.6-ALPHA. I am using the Create Flavored modpack version 5.10.

**Comment by leon-o** [comment]
Do these problems still occur in version 0.2.0?

**Comment by PapaDimitri** [comment]
It works with instancing backend. But on batching it does this:
![2023-06-12_10 48 40](https://github.com/leon-o/iris-flw-compat/assets/127027659/dd03b479-6311-45f0-881d-8dd5c1797666)

**Comment by leon-o** [comment]
Batching is not supported.
