### ISSUE TITLE
Visual Bug with Windmills and Chutes (Forge 1.18.2)

### ISSUE THREAD

**Issue by crowteaz** [leon-o/iris-flw-compat#40]
For some reason moving Windmills are showing through Chutes. (And _only_ moving Windmills to my knowledge)

![Screenshot_20230318_102812](https://user-images.githubusercontent.com/119660091/226112773-3864a490-6a55-4b14-95d1-5b68e2681ef2.png)
This is how the machine is supposed to look (no shaders, mod is on though).

![Screenshot_20230318_102847](https://user-images.githubusercontent.com/119660091/226112792-7c2b821b-7988-4231-91f7-9cc5f783cad1.png)
This is how it looks with shaders on. (Sildur's Vibrant v1.50 lite)

I'm running this on Forge 1.18.2 40.2.0, running on Linux (Kubuntu 22.10, X11 mode,) via MultiMC, with Create version 0.5.0.i, Flywheel version 0.6.8.a, Oculus 1.4.3a, Oculus Flywheel Compat version 0.1.8-BETA, and a few other mods I can list if needed.
Sorry if this is formatted weird at all or if this is a known bug, I'm not incredibly familiar with reporting bugs.

---

EDIT: After some more testing, this seems to _only_ happen when there are no blocks between the Windmill and Chutes. I placed a wall between the two and it doesn't show up anymore.

![Screenshot_20230318_110145](https://user-images.githubusercontent.com/119660091/226113896-353ce98f-e243-4b13-b074-bb680503acf3.png)
This is the machine from the side (with the wall) for reference.

EDIT 2: After even more testing, it appears through Grass blocks too.

![Screenshot_20230318_113904](https://user-images.githubusercontent.com/119660091/226115732-eca6f6d7-d7e0-41fc-82fe-1cf69f46505c.png)

**Comment by leon-o** [comment]
Are you using Sildur's Vibrant?

**Comment by crowteaz** [comment]
Yes.
