### ISSUE TITLE
移动结构上的光源不发光

### ISSUE THREAD

**Issue by ghost** [leon-o/iris-flw-compat#43]
![2023-04-13_22 47 47](https://user-images.githubusercontent.com/129179911/231797738-93987ea2-3ebe-4c63-8038-d630318922ac.png)
如禁用batching或instancing引擎则无该问题
mod版本:oculus-flywheel-compat-1.19.2-0.1.8-BETA

**Comment by Spade14SS** [comment]
作者您好，我也在做列车的时候 遇到了移动结构光源不发光的问题。版本是OculusFlwCompat-1.18.2-0.2.1。请问这有解决方法了吗？谢谢您

**Comment by leon-o** [comment]
Fixed by commit bef9d93.
