### ISSUE TITLE
箱子渲染问题

### ISSUE THREAD

**Issue by ghost** [leon-o/iris-flw-compat#45]
![2023-04-29_19 12 58](https://user-images.githubusercontent.com/129179911/235299699-97206aea-fe3c-45de-9aa4-4f8adc43eb63.png)
开启batching/instancing引擎前

![2023-04-29_19 10 26](https://user-images.githubusercontent.com/129179911/235299724-e02b5f71-43e5-4cbd-822c-a32db42d0f8b.png)
开启batching/instancing引擎后（右半部分阴影异常）

mod版本:oculus-flywheel-compat-1.19.2-0.1.8-BETA

**Comment by leon-o** [comment]
用的是BSL吗？试一下最新的0.2.0看看还会不会这样。

**Comment by leon-o** [comment]
现在应该没这个问题了吧。
