### ISSUE TITLE
Not compatible anymore with Iris 1.6.2

### ISSUE THREAD

**Issue by Shadow091995** [leon-o/iris-flw-compat#46]
Iris 1.6.2 dropped today and shaders don't enable with the Flywheel compat mod enabled at all anymore.
As soon as the compat mod is out, they work again.
[latest.log](https://github.com/leon-o/iris-flw-compat/files/11375650/latest.log)

**Comment by gittibene** [comment]
can confirm

**Comment by ganderhero** [comment]
This same issue had been plaguing me for the past 3 days, the only fix I just found out was to use iris 1.6.0

**Comment by Sooperfish** [comment]
Same issue. https://mclo.gs/D3F7rpC

**Comment by leon-o** [comment]
The new version 0.2.0 now supports iris 1.6.2.
