### ISSUE TITLE
将flywheel引擎设置为batching时出现渲染错误

### ISSUE THREAD

**Issue by Miaochan** [leon-o/iris-flw-compat#47]
![2023-05-11_21 55 54](https://github.com/leon-o/iris-flw-compat/assets/129179911/6802422a-12df-49f1-a18f-49d3a59dc019)
![2023-05-11_22 04 49](https://github.com/leon-o/iris-flw-compat/assets/129179911/65c29cdd-a141-4517-8619-b36207444dd8)

如图，安装此mod后将flywheel引擎设置为batching时有概率出现一系列渲染错误。（如GUI消失，游戏出现黑色条纹等）
mod版本:oculus-flywheel-compat-1.19.2-0.1.8-BETA

**Comment by leon-o** [comment]
为什么设置成batching呢？这个mod只支持设置成instancing，而且设置成instancing性能更好。

**Comment by leon-o** [comment]
设置成Instancing会有渲染错误吗？是什么样的渲染错误？试试看最新版还会不会有渲染错误。
