### ISSUE TITLE
游戏崩溃

### ISSUE THREAD

**Issue by nageih** [leon-o/iris-flw-compat#48]
1.19.2fabric0.14.19
iris-flywheel-compat-1.19.2-0.1.9
create-fabric-0.5.0.i-1003
iris-mc1.19.2-1.6.2
[latest.txt](https://github.com/leon-o/iris-flw-compat/files/11469693/latest.txt)

**Comment by leon-o** [comment]
新的0.2.0版本支持iris 1.6了。
