### ISSUE TITLE
Shader Issue - Rethinking Voxels

### ISSUE THREAD

**Issue by SirOMGitsYOU** [leon-o/iris-flw-compat#49]
Just tried using this with Rethinking Voxels shaderpack and it looks to be having some funky weirdness going on
![image](https://github.com/leon-o/iris-flw-compat/assets/20475516/394d6178-e5f2-46e1-96f5-2b1d2cc42006)

Anything that can be done to remedy this? 

The lava gets bright again when going away from it but gets shadow/darker when upclose

**Comment by leon-o** [comment]
It should have been fixed in the latest version 0.2.0. 🎉
