### ISSUE TITLE
Bells Werid graphical issue

### ISSUE THREAD

**Issue by SirOMGitsYOU** [leon-o/iris-flw-compat#50]
When placing or seeing a bell in the vicinity the following happens - https://cdn.discordapp.com/attachments/658743137174421504/1109144996935905341/image.png,

This happens as soon as the bell comes into render distance and the actual bell is invisible.

**Comment by leon-o** [comment]
Are you using oculus or iris and what version of iris are you using？
What version of this mod are you using?
I need more information to help me troubleshoot the problem . :relaxed:

**Comment by SirOMGitsYOU** [comment]
> Are you using oculus or iris and what version of iris are you using？ What version of this mod are you using? I need more information to help me troubleshoot the problem . ☺️

Oculus was in-use, Verison 1.5.2.
