### ISSUE TITLE
[1.19.2forge]使用部分光影开启PBR资源包时出现渲染问题

### ISSUE THREAD

**Issue by ghost** [leon-o/iris-flw-compat#52]
Oculus于最新版中添加了对PBR资源包的支持
如果在引擎设置为instancing时启用pbr材质包并开启BSL的pbr材质支持功能 则部分原版的方块实体以及绝大多数的机械动力方块与动态结构将出现渲染问题
![2023-06-14_03 09 03](https://github.com/leon-o/iris-flw-compat/assets/129179911/63cb81ce-8cc6-4ff8-9267-97e657fc1fd6)
启用instancing引擎时

![2023-06-14_03 09 38](https://github.com/leon-o/iris-flw-compat/assets/129179911/89a9b138-5da9-48e1-9497-4f3a28d406d8)
禁用instancing引擎时

除BSL外还于Astralex、Kappa中发现了此问题 不过其他光影需在开启高级材质功能的同时打开视差贴图选项（如Astralex）
部分经测试表现正常的光影:Complementary系列、Sildur's Vibrant Shaders

测试用材质包:[Another Vanilla PBR](https://www.curseforge.com/minecraft/texture-packs/avpbr)、[Vanilla PBR](https://www.curseforge.com/minecraft/texture-packs/vanilla-pbr)

**Comment by leon-o** [comment]
可以提供详细的mod列表吗？
我也用了PBR材质，Kappa、photon上都是正常的。:dizzy_face:

**Comment by onenok** [comment]
感覺是動畫材質(或者之類的東西)出現問題

**Comment by vn-killer** [comment]
我用的是photon main 光影，出现了上述问题，想问一下有没有推荐的解决办法
