### ISSUE TITLE
Crashing during mod loading screen

### ISSUE THREAD

**Issue by Devilswarchild** [leon-o/iris-flw-compat#57]
MC Version: 1.20.1
Forge Version: 47.1.0
mod version: oculus-flywheel-compat-1.20.1-0.2.0.jar

[debug.log](https://github.com/leon-o/iris-flw-compat/files/11992385/debug.log)
[latest.log](https://github.com/leon-o/iris-flw-compat/files/11992386/latest.log)
[launcher_log.txt](https://github.com/leon-o/iris-flw-compat/files/11992387/launcher_log.txt)

modlist:
[Cooking for Blockheads (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Modonomicon (by kli_kli)](https://www.curseforge.com/minecraft/mc-mods/modonomicon)
[Enhanced Farming (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/enhanced-farming)
[Reap Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/reap-mod)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
[Corail Pillar (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-pillar)
[Lithereal (by TheLightBlueGame)](https://www.curseforge.com/minecraft/mc-mods/lithereal)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[Croptopia (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/croptopia)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[Creeper Firework (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/creeper-firework)
[Extreme Reactors (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/extreme-reactors)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Corail Woodcutter (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-woodcutter)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[CTD Core (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/ctd-core)
[MidnightLib (by TeamMidnightDust)](https://www.curseforge.com/minecraft/mc-mods/midnightlib)
[Additional Lanterns (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/additional-lanterns)
[Craftable Horse Armour & Saddle [CHA&S] (by EwyBoy)](https://www.curseforge.com/minecraft/mc-mods/cha-s)
[Epic Samurai's (by VeroxUniverse)](https://www.curseforge.com/minecraft/mc-mods/epic-samurais)
[Mo' Glowstone (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/mo-glowstone)
[FPS Monitor (by EwyBoy)](https://www.curseforge.com/minecraft/mc-mods/fps-monitor)
[Get It Together, Drops! (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Not Enough Crashes (Forge) (by NatanFudge)](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge)
[Vanilla Plus Tools (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/vanilla-tools)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Large Ore Deposits (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/large-ore-deposits)
[Catalogue (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/catalogue)
[Dense Ores - Abundant! (by NewJumperr)](https://www.curseforge.com/minecraft/mc-mods/dense-ores-abundant)
[Fast Portals (by gluegunner4)](https://www.curseforge.com/minecraft/mc-mods/fast-portals)
[Portable Crafting Table (by 00theblackwolf00)](https://www.curseforge.com/minecraft/mc-mods/portable-crafting-table)
[Almost Unified (by AlmostReliable)](https://www.curseforge.com/minecraft/mc-mods/almost-unified)
[Cristel Lib (by Cristelknight)](https://www.curseforge.com/minecraft/mc-mods/cristel-lib)
[Visual Overhaul (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/visual-overhaul)
[Wormhole (Portals) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/wormhole-portals)
[Log Begone (by AzureDoomC)](https://www.curseforge.com/minecraft/mc-mods/log-begone)
[Bigger Stacks (by thanksihadtosignupforthis)](https://www.curseforge.com/minecraft/mc-mods/bigger-stacks)
[Inventory Essentials (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/inventory-essentials)
[Immersive Paintings [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-paintings)
[Armourer's Workshop (by RiskyKen)](https://www.curseforge.com/minecraft/mc-mods/armourers-workshop)
[TrashSlot (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/trashslot)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Chunk Animator (by Lumien231)](https://www.curseforge.com/minecraft/mc-mods/chunk-animator)
[SmartBrainLib (Forge/Fabric/Quilt) (by Scimiguy)](https://www.curseforge.com/minecraft/mc-mods/smartbrainlib)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[PlayerRevive (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/playerrevive)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Mo' Glowstone Lamps (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/mo-glowstone-lamps)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Erroring Entity Remover Reforged (by AzureDoomC)](https://www.curseforge.com/minecraft/mc-mods/erroring-entity-remover-reforged)
[ForgeEndertech (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/forgeendertech)
[GravelMiner (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/gravelminer)
[Additional Structures (by XxRexRaptorxX)](https://www.curseforge.com/minecraft/mc-mods/additional-structures)
[Occultism (by kli_kli)](https://www.curseforge.com/minecraft/mc-mods/occultism)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Variant Crafting Tables [Forge] (by Kitteh6660)](https://www.curseforge.com/minecraft/mc-mods/variant-crafting-tables)
[Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
[Structurize (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/structurize)
[Just Another Rotten Flesh to Leather Mod (by alexdaum1)](https://www.curseforge.com/minecraft/mc-mods/just-another-rotten-flesh-to-leather-mod)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[The Graveyard (FORGE) (by finallion_13)](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-forge)
[Connected Glass (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/connected-glass)
[Domum Ornamentum (by OrionOnline)](https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum)
[Advanced Chimneys (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/advanced-chimneys)
[Game Menu Mod Option [Forge] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption)
[Fastload (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/fastload)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Yeetus Experimentus (by Sunekaer)](https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus)
[Storage Racks (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/storage-racks)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[BlockUI (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/blockui)
[Double Doors (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/double-doors)
[Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
[ZeroCore 2 (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/zerocore)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[KleeSlabs (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/kleeslabs)
[Applied Energistics 2 (by thetechnici4n)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
[Immersive Aircraft [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft)
[The Undergarden (by Quek04)](https://www.curseforge.com/minecraft/mc-mods/the-undergarden)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Farsight [Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight)
[Exotelcraft (by TKD_Kedis)](https://www.curseforge.com/minecraft/mc-mods/exotelcraft)
[Packed Up (Backpacks) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/packed-up-backpacks)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)

**Comment by leon-o** [comment]
[08Jul2023 15:54:40.322] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'flywheel', Requested by: 'create', Expected range: '[0.6.9,0.6.10)', Actual version: '0.6.8.a'
	Mod ID: 'minecraft', Requested by: 'flywheel', Expected range: '[1.19.2,1.20)', Actual version: '1.20.1'
	Mod ID: 'flywheel', Requested by: 'irisflw', Expected range: '[0.6.9,)', Actual version: '0.6.8.a'
	
Just remove the flywheel you installed. The version is wrong and you don't need to add it manually because the Create already contained it.
