### ISSUE TITLE
Incompatable with Latest Version Of Create

### ISSUE THREAD

**Issue by ACrazyD** [leon-o/iris-flw-compat#66]
Versions As Follows
MC: 1.19.2
Forge: 43.2.14
Create: 0.5.1c
Oculus: 1.6.4
Compact: 0.2.1

Error Logged

Missing or unsupported mandatory dependencies:
	Mod ID: 'flywheel', Requested by: 'create', Expected range: '[0.6.9,0.6.10)', Actual version: '0.6.8.a'
	
Crash Report: [https://hastebin.com/share/geyariyeje.yaml](https://hastebin.com/share/geyariyeje.yaml)

The issue only happens when updating off of Create Version 0.5.1b

**Comment by ACrazyD** [comment]
That version of flywheel is the version packed into the create jar now (I Admit, I find it a pain they packed them together but now it is, and they removed the extra mod)

**Comment by MrRedstoneToGo** [comment]
Isn't Embeddium/Rubidium needed?

**Comment by MrRedstoneToGo** [comment]
Update all the mods and forge, then it should work

**Comment by ACrazyD** [comment]
Fixed btw, Ages ago, closeing this
