### ISSUE TITLE
[1.19.2 Fabric] extremely weird bug and console spam with the latest version of bliss

### ISSUE THREAD

**Issue by glittermutt** [leon-o/iris-flw-compat#68]
whenever i turn on the [bliss](https://www.curseforge.com/minecraft/customization/bliss-shader) shaderpack, this happens. an invisible minecart appears and this black bar that won't go anywhere
![2023-08-31_18 59 07](https://github.com/leon-o/iris-flw-compat/assets/134949309/28e090c3-43cc-4443-bc46-7b4f41eaa744)
![2023-08-31_18 59 12](https://github.com/leon-o/iris-flw-compat/assets/134949309/2c13f7fd-36f4-4474-a4c8-b29dd5027425)
[here's](https://files.catbox.moe/8kemsv.log) the log file, pleaase help

**Comment by glittermutt** [comment]
update: it only happens on the instancing backend. HOWEVER, the batching backend seems to be bugged too - here are pictures, the first one is bliss with instancing on, the latter one is bliss with batching on
![2023-08-31_20 17 53](https://github.com/leon-o/iris-flw-compat/assets/134949309/10c91d8a-2726-4a55-ac91-76c5a71622e0)
![2023-08-31_20 18 27](https://github.com/leon-o/iris-flw-compat/assets/134949309/4d390c09-6360-43b7-98e6-bd15e0c9661e)

**Comment by leon-o** [comment]
It should be fixed by 3d07f64.
