### ISSUE TITLE
与complementary reimagined 5.0.1和euphoria patches的兼容性问题

### ISSUE THREAD

**Issue by ghost** [leon-o/iris-flw-compat#73]
1.在flywheel backend设置为instancing的情况下，打开[complementary reimagined 5.0](https://modrinth.com/shader/complementary-reimagined/version/r5.0.1)的设置界面>Materials>Integrated Materials将Generated Normals设置为on并将RP support设置为Integrated PBR+后，大箱子的中间会出现奇怪的裂缝:
![2023-09-15_23 09 18](https://github.com/leon-o/iris-flw-compat/assets/129179911/94e3bb77-c0a3-485a-9af4-cfd2f8c4ce23)
![2023-09-15_23 10 48](https://github.com/leon-o/iris-flw-compat/assets/129179911/8535a9f3-a076-471a-b96c-ea2e5b2d640b)

将backend设置为off后即可恢复正常:
![2023-09-15_23 09 38](https://github.com/leon-o/iris-flw-compat/assets/129179911/89fa632e-e2a8-4b27-914d-39968dc2fa7f)
![2023-09-15_23 11 34](https://github.com/leon-o/iris-flw-compat/assets/129179911/edceeca0-6ca8-4692-8f30-2a4e3b09f42f)

相关必要选项：
![2023-09-15_23 27 14](https://github.com/leon-o/iris-flw-compat/assets/129179911/5e408c8c-502d-4922-916a-ed2c9ae5ec5c)
![2023-09-15_23 29 49](https://github.com/leon-o/iris-flw-compat/assets/129179911/d6b841fd-cf1a-44b4-8fcf-6248bc9e148b)

**Comment by DaddyKami** [comment]
i have the exact same issue using euphoria patches, chests without top and random black boxes flying around

**Comment by leon-o** [comment]
Fixed by commit 3d07f64.
