### ISSUE TITLE
Brightly lit contraptions

### ISSUE THREAD

**Issue by codegoose** [leon-o/iris-flw-compat#82]
Hi there,

I noticed that contraptions are not affected by shader lighting in my server so I went digging around. I added some code to output the results of the vertex shader transformations to the filesystem so I could take a look:

```glsl
void main() {
  v = FLWCreateVertex();
  vertex(v);
  v.light = vec2(0, 0.85f);
  vec3 skewedNormal = v.normal + vec3(0.5f, 0.5f, 0.5f);
  _flw_tangent = vec4(normalize(skewedNormal - v.normal * dot(skewedNormal, v.normal)).xyz, 1.0f);
  _flw_patched_vertex_pos = FLWVertex(v);
  texCoord = (gl_TextureMatrix[0] * vec4(v.texCoords, 0, 1)).xy;
  vertexColor = v.color.rgb;
  vec3 vertexNormal = fastNormalize(v.normal);
  vec3 vertexTangent = fastNormalize(_flw_tangent.xyz);
  vertexPos = gbufferModelViewInverse * (gl_ModelViewMatrix * inverse(gl_ProjectionMatrix * gl_ModelViewMatrix) * _flw_patched_vertex_pos);
  TBN = mat3(gbufferModelViewInverse) * (gl_NormalMatrix * mat3(vertexTangent, cross(vertexTangent, vertexNormal) * sign(_flw_tangent.w), vertexNormal));
  lmCoord = saturate((vec4(max(v.light, texture3D(uLightVolume, BoxCoord).rg) * 255.0f, 0, 1)).xy * 0.00416667f);
  gl_Position = _flw_patched_vertex_pos;
}
```

(This is with the Super Duper Vanilla pack.)

I noticed that the `ShaderPatcherBase.java` is inserting this into Create's `passthrough.vert` shader:

```glsl
v = FLWCreateVertex();
vertex(v);
v.light = vec2(0,0.85);
```

This has the effects of causing the contraptions to be very brightly lit:

![2023-11-26_20 11 52](https://github.com/leon-o/iris-flw-compat/assets/38875053/05ea541d-7d0a-4811-ba60-664dd877f233)

Upon removing the `v.light = vec2(0,0.85);` line, contraptions go back to normal:

![2023-11-26_20 12 10](https://github.com/leon-o/iris-flw-compat/assets/38875053/ac9a5aa8-f147-4bd7-be30-9227967d2c48)

I'm just wondering what the reasoning behind this is as I don't have full context of what's going on, really.

**Comment by Hr0bak** [comment]
I have the exact same problem! But I'm a very superficial user( I would be so grateful if you could explain where exactly to find this file, and the document in it, where I can edit this setting and fix the problem.

**Comment by codegoose** [comment]
> I have the exact same problem! But I'm a very superficial user( I would be so grateful if you could explain where exactly to find this file, and the document in it, where I can edit this setting and fix the problem.

It's in here: https://github.com/leon-o/iris-flw-compat/blob/6f8b46b2f0270fc5a7feea354dd2b03c96a295af/src/main/java/top/leonx/irisflw/transformer/ShaderPatcherBase.java#L40

I had just removed that line and rebuilt the JAR.
