### ISSUE TITLE
使用Iris & Oculus Flywheel Compat1.20.1-0.2.1时会无法读取任何材质

### ISSUE THREAD

**Issue by bbz-233** [leon-o/iris-flw-compat#85]
**错误日志**
[latest.log](https://github.com/leon-o/iris-flw-compat/files/13628900/latest.log)

**错误详情**
每次启动游戏或者应用材质包更改时都会弹出"重载资源失败"
无法读取任何材质包的mcmeta文件

**Comment by PsssssssHao** [comment]
你是不是装了I18nUpdateMod或者汉化资源包。

**Comment by leon-o** [comment]
你把你的资源包都删了，一个一个加回去，看看是哪个出了问题。

**Comment by bbz-233** [comment]
> 你是不是装了I18nUpdateMod或者汉化资源包。

是的，装了个i18n

**Comment by bbz-233** [comment]
> 你把你的资源包都删了，一个一个加回去，看看是哪个出了问题。

标题你是一点没看😄

**Comment by leon-o** [comment]
不是这个mod导致的
