### ISSUE TITLE
Contraptions on linear/radial chasis rendering black

### ISSUE THREAD

**Issue by noolaan** [leon-o/iris-flw-compat#9]
Using version Minecraft version 1.18.2, iris-flywheel-compat version 0.1.5, and flywheel version 0.6.5.
Moving objects on the different types of chassis seem to render as black, such as the spinning part of the mechanical harvester, or connecting part of the portable storage interface. Also notice how the stationary portable storage interface looks fine, it only seems to happen when moving via chassis.

![image](https://user-images.githubusercontent.com/32991023/186063390-601009c2-6b4e-4b11-9c37-6b9ee52ee0bf.png)

**Comment by noolaan** [comment]
Also I am using Complementary, however the issue also persists with BSL, Sildurs, and any other supported shaders by this mod.

**Comment by craigprime** [comment]
I'm having the same problem. 

Minecraft 1.18.2
Forge 40.1.80
Oculus 1.2.5a
Flywheel 0.6.5
Oculus Flywheel Compat 1.2.5a

Would love to see an update!

**Comment by leon-o** [comment]
This bug has been fixed in 0.1.7b.
