### ISSUE TITLE
Better Minecraft Mod Pack 1.20.1 + Create Issue

### ISSUE THREAD

**Issue by Swordy-Lab** [leon-o/iris-flw-compat#94]
Hi, I am currently using the following mod pack with Create implemented and would like to use shader and came across your mod. However, it crashes after I load a world. The error code is attached

Link to the modpack: https://www.curseforge.com/minecraft/modpacks/better-mc-fabric-bmc1

[crash-2024-01-21_03.25.57-client.txt](https://github.com/leon-o/iris-flw-compat/files/13999879/crash-2024-01-21_03.25.57-client.txt)

It would be really nice if you could take a look, because unfortunately I'm completely at the end of my rope. I know that a few mixins happen and that it probably has something to do with the owo plugin, but I don't really have a solution :/

**Comment by PaulRV0709** [comment]
I have the same problem. I can send modpack list if it helps.

**Comment by leon-o** [comment]
I've noticed an error: java.lang.NoSuchMethodError: 'java.lang.Iterable.net.coderbot.iris.gl.shader.StandardMacros.createStandardEnvironmentDefines()'. 

This is due to the incompatibility with the newer version of Iris that you are using. 
The latest version 0.2.4 should have fixed this issue.
