### ISSUE TITLE
I can't join server the game when I added this mod (fabric, 1.20.1)

### ISSUE THREAD

**Issue by MerzouuuGH** [leon-o/iris-flw-compat#95]
Log:
[latest.log](https://github.com/leon-o/iris-flw-compat/files/14028512/latest.log)
From what I see, I need to have flywheel fabric for 1.20.1, but it hasn't been created, how can I fix it?

**Comment by Tempest-5ky** [comment]
Same issue, here's the specific crash: https://mclo.gs/osTdoW9

Fabric 1.20.1, mod version 0.2.1

**Comment by leon-o** [comment]
Try the latest version 0.2.4 and see if it resolves the issue.

**Comment by Tempest-5ky** [comment]
Joining the server seems to work, but if I use a shader... this happens. 
![image](https://github.com/leon-o/iris-flw-compat/assets/99220350/4acf81f9-fdd1-4226-99d3-b4e6db7cb711)

**Comment by leon-o** [comment]
Use the instanced backend and try the latest version. The issue should has been fixed. Open a new issue if you have any other problems.
