### ISSUE TITLE
Crash with newer versions of sodium

### ISSUE THREAD

**Issue by Sooperfish** [leon-o/iris-flw-compat#99]
I'm running create-sodium-fix fork that supports the newest version of sodium (create-sodium-fix-0.5.1-d-build.1161+mc1.20.1), and whenever I place a create object in a test world, with shaders enabled, I crash. 

Minecraft version: 1.20.1
Mods:
Fabric API 0.92.0
Sodium 0.5.8
create-sodium-fix-0.5.1-d-build.1161
Indium 1.0.30
Iris 1.6.17
Irisflw >0.2.1 (latest gradlew build)

It's a bit of a mess right now trying to run create with shaders on newer versions of sodium, I hope the create-fabric devs support sodium 0.5 soon.

I tried with two different forks of create-sodium-fix:
- https://github.com/Mukul1127/Create-Sodium-Fix/releases/tag/mc1.20.1%2Fsodium-fix
log: - https://mclo.gs/KDWndWh
- https://github.com/AsgerJon/Create-lol/actions/runs/7150968621
log: - https://mclo.gs/Ixjj3rI

**Comment by leon-o** [comment]
The issue has been addressed in version 0.2.4 .
